### ISSUE TITLE
Can we use dropbox storage now?

### ISSUE THREAD

**Issue by gitkiwikiwi** [AnthonyRonning/Agora#17]

**Comment by AnthonyRonning** [comment]
Good question, unfortunately it looks like it was removed due to limitations with the API: https://forum.blockstack.org/t/where-is-the-source-code-for-todos-sample-app/6173/2

**Comment by gitkiwikiwi** [comment]
https://diffuse.sh/  this site allows users use dropbox and blockstack to
store users' data. please Check it out.

AnthonyRonning <notifications@github.com> 于2019年3月1日周五 下午1:23写道：
